/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lhsmtvmtxvyudcboqyrl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxoc210dm10eHZ5dWRjYm9xeXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNTc3NDEsImV4cCI6MjA3MjgzMzc0MX0.iCbFPdRqkZB7LLcWrB-ffwF-sz20A3ySo4th7q_oCzU"